---
title: "Untitled"
author: "Umit Taner"
date: "August 16, 2016"
output: 
  ioslides_presentation: 
    smaller: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Global Temperature change


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library("highcharter")
library("readr")
library("dplyr")
library("tidyr")
library("lubridate")
library("purrr")
library("viridis")

options(
  highcharter.theme = hc_theme_darkunica(
    chart  = list(
      style = list(fontFamily = "Roboto Condensed"),
      backgroundColor = "#323331"
    ),
    yAxis = list(
      gridLineColor = "#B71C1C",
      labels = list(format = "{value} C", useHTML = TRUE)
    ),
    plotOptions = list(series = list(showInLegend = FALSE))
  )
)

df <- read_csv(
  "https://raw.githubusercontent.com/hrbrmstr/hadcrut/master/data/temps.csv")

df <- df %>%
  mutate(date = ymd(year_mon),
    tmpstmp = datetime_to_timestamp(date),
    year = year(date),
    month = month(date, label = TRUE),
    color_m = colorize(median, viridis(10, option = "B")),
    color_m = hex_to_rgba(color_m, 0.65))

dfcolyrs <- df %>%
  group_by(year) %>%
  summarise(median = median(median)) %>%
  ungroup() %>%
  mutate(color_y = colorize(median, viridis(10, option = "B")),
    color_y = hex_to_rgba(color_y, 0.65)) %>%
  select(-median)

df <- left_join(df, dfcolyrs, by = "year")


lsseries <- df %>%
  group_by(year) %>%
  do(
    data = .$median,
    color = first(.$color_y)) %>%
  mutate(name = year) %>%
  list.parse3()

hc1 <- highchart() %>%
  hc_chart(polar = TRUE) %>%
  hc_plotOptions(
    series = list(
      marker = list(enabled = FALSE),
      animation = TRUE,
      pointIntervalUnit = "month")
  ) %>%
  hc_legend(enabled = FALSE) %>%
  hc_xAxis(type = "datetime", min = 0, max = 365 * 24 * 36e5,
    labels = list(format = "{value:%B}")) %>%
  hc_tooltip(headerFormat = "{point.key}",
    xDateFormat = "%B",
    pointFormat = " {series.name}: {point.y}") %>%
  hc_add_series_list(lsseries)

lsseries2 <- df %>%
  group_by(year) %>%
  do(
    data = .$median,
    color = "transparent",
    enableMouseTracking = FALSE,
    color2 = first(.$color_y)) %>%
  mutate(name = year) %>%
  list.parse2()


hc11 <- highchart() %>%
  hc_chart(polar = TRUE) %>%
  hc_plotOptions(series = list(
    marker = list(enabled = FALSE),
    animation = TRUE,
    pointIntervalUnit = "month")) %>%
  hc_legend(enabled = FALSE) %>%
  hc_title(text = "Animated Spiral") %>%
  hc_xAxis(type = "datetime", min = 0, max = 365 * 24 * 36e5,
    labels = list(format = "{value:%B}")) %>%
  hc_tooltip(headerFormat = "{point.key}", xDateFormat = "%B",
    pointFormat = " {series.name}: {point.y}") %>%
  hc_add_series_list(lsseries2) %>%
  hc_chart(
    events = list(
      load = JS("

        function() {
        console.log('ready');
        var duration = 16 * 1000
        var delta = duration/this.series.length;
        var delay = 2000;

        this.series.map(function(e){
        setTimeout(function() {
        e.update({color: e.options.color2, enableMouseTracking: true});
        e.chart.setTitle({text: e.name})
        }, delay)
        delay = delay + delta;
        });

        }
        ")
      )
      )

hc11

```

